name: Weekly Enrich & Sync to Webflow
on:
  schedule:
    - cron: "0 9 * * 1"   # Mondays 09:00 UTC (3/4 AM US time). Change as you like.
  workflow_dispatch:      # allow manual run
  push:
    paths:
      - "content/projects.json"  # if you manually edit JSON, we'll sync on push

permissions:
  contents: write  # needed to commit the enriched JSON back

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1) Enrich JSON from GitHub repo metadata
      - name: Enrich projects.json with GitHub metadata
        run: node scripts/enrich-projects.mjs
        env:
          GH_META_TOKEN: ${{ secrets.GH_META_TOKEN }}  # optional but recommended to avoid rate limits

      # 2) Commit changes if enrichment modified the file
      - name: Commit enriched JSON (if changed)
        run: |
          if [[ -n "$(git status --porcelain content/projects.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add content/projects.json
            git commit -m "chore: enrich projects.json (weekly)"
            git push
          else
            echo "No changes to commit."
          fi

      # 3) Sync to Webflow CMS and publish
      - name: Sync to Webflow CMS
        run: node scripts/sync-webflow-projects.mjs
        env:
          WEBFLOW_TOKEN: ${{ secrets.WEBFLOW_TOKEN }}
          WEBFLOW_COLLECTION_ID: ${{ secrets.WEBFLOW_COLLECTION_ID }}
